sudo: required
services:
- docker
env:
  global:
    - secure: F9Gs/VuSm3f/Y6lv2V3l1mBeqxbDrctqADd78nC1TFDNKJB7RNqhCdEVF+TyfM9/L97qGm+5WkTi5UeOuHtLFUNpCjPPtFINB9SVDYoRAg2O7hjjjL7N1u0RZyYgcmMucZn/H3jepcwSFge4EsGrDvCTD31kHAbHWeI1R0u9bSS1GI9iKDYmcgM/6c9kWfoNXSepTJQB5C81K5y+6jNP4kAIXqxnUNIB/y/y4VP6JW8jPNPKxE9HJ4fswDJuHgS8bJMisOKj6NeLKfdX/N32nLjnYWdKkga4s2rzNWldaAHAW3jt8/nPZKplS0rC/vrlITg9U7QBdxuh/dbgm5vf8V7jRrHRUAOfzMg0ITsnFgdNIwN6Vmc0NgaokIfJBPLKYdDgWZdCEsy5RQ/Ch0DqtSxVJyW9pkZQXwxkOguSf20Nu9frm6heTfqKwrWqY3jGobnxJLuRuwNIYvCnBUM338VI2HyhlYODVp67FwPcE8MfR/QN4UzwP5caxKMjNxriTWaQkYtOE1hbYh8f7QfffWGUzVWaNxJDZWS0izMo5EeYxNBTZY5zZ1d6t4UoddvNANTHQt5LiA8iJiD6HKbFOkbu96duiYf7Z+rKqDWN7wDrQnMuMi04pqm25i1dHmI4lNNyhgs0m6lLO38NHKEcmTo8P8apcDcdq8Q3tDHeQFo=
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth activate-service-account --key-file service-account.json
    - gcloud config set project multi-k8s-276212
    - gcloud config set compute/zone asia-southeast1-a
    - gcloud container clusters get-credentials multi-k8s
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t "$DOCKER_USERNAME"/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true "$DOCKER_USERNAME"/react-test npm run test
deploy:
    provider: script
    script: bash ./deploy.sh
    on:
        branch: master